// src/lib/components/ActionButtons.svelte
<script lang="ts">
  import { HeartIcon, XIcon } from 'lucide-svelte';

  let { 
    disabled = false,
    onlike,
    ondislike 
  }: { 
    disabled?: boolean;
    onlike?: () => void;
    ondislike?: () => void;
  } = $props();
</script>

<div class="flex justify-center items-center gap-6 mt-6">
  <button
    onclick={ondislike}
    {disabled}
    class="flex items-center justify-center h-16 w-16 rounded-full border-2 border-red-200 bg-white shadow-lg hover:bg-red-50 hover:border-red-400 hover:text-red-500 transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed group active:scale-90"
    aria-label="Dislike"
  >
    <XIcon class="h-8 w-8 group-hover:scale-110 transition-transform text-red-400" />
  </button>

  <button
    onclick={onlike}
    {disabled}
    class="flex items-center justify-center h-16 w-16 rounded-full border-2 border-pink-200 bg-white shadow-lg hover:bg-pink-50 hover:border-pink-400 hover:text-pink-500 transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed group active:scale-90"
    aria-label="Like"
  >
    <HeartIcon class="h-8 w-8 group-hover:scale-110 transition-transform text-pink-400" />
  </button>
</div>

// src/app/components/ActionButtons.tsx
"use client"

import { Button } from "@/app/components/ui/button"
import { Heart, Star, X } from "lucide-react"

interface ActionButtonsProps {
  onDislike: () => void
  onLike: () => void
  onSuperLike?: () => void
}

export default function ActionButtons({ onDislike, onLike, onSuperLike }: ActionButtonsProps) {
  return (
    <div className="flex justify-center items-center gap-4 mt-6">
      <Button
        onClick={onDislike}
        size="icon"
        variant="outline"
        className="h-14 w-14 rounded-full border-2 border-muted bg-background shadow-md hover:bg-muted/10 hover:text-rose-500 transition-all duration-200"
      >
        <X className="h-7 w-7" />
        <span className="sr-only">Dislike</span>
      </Button>

      {onSuperLike && (
        <Button
          onClick={onSuperLike}
          size="icon"
          variant="outline"
          className="h-12 w-12 rounded-full border-2 border-muted bg-background shadow-md hover:bg-muted/10 hover:text-blue-500 transition-all duration-200"
        >
          <Star className="h-6 w-6" />
          <span className="sr-only">Super Like</span>
        </Button>
      )}

      <Button
        onClick={onLike}
        size="icon"
        variant="outline"
        className="h-14 w-14 rounded-full border-2 border-muted bg-background shadow-md hover:bg-muted/10 hover:text-pink-500 transition-all duration-200"
      >
        <Heart className="h-7 w-7" />
        <span className="sr-only">Like</span>
      </Button>
    </div>
  )
}
