// src/lib/components/NewCard.svelte
<script lang="ts">
  import { MapPinIcon, InfoIcon } from 'lucide-svelte';
  import type { ExploreProfile } from '$lib/types/explore';

  let { profile }: { profile: ExploreProfile } = $props();

  const mainPhoto = $derived(
    profile.photos && profile.photos.length > 0 
      ? profile.photos[0] 
      : `https://ui-avatars.com/api/?name=${profile.fullname}&size=500&background=random`
  );
</script>

<div class="relative w-full aspect-3/4 bg-white rounded-3xl overflow-hidden shadow-xl select-none group">
  <img 
    src={mainPhoto} 
    alt={profile.fullname} 
    class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
    draggable="false"
  />

  <div class="absolute inset-0 bg-linear-to-t from-black/90 via-black/30 to-transparent opacity-90"></div>

  <div class="absolute bottom-0 left-0 w-full p-6 text-white">
    <div class="flex items-end justify-between mb-2">
      <div class="flex flex-col">
        <h2 class="text-3xl font-bold tracking-tight flex items-baseline gap-2 text-shadow">
          {profile.fullname}
          <span class="text-xl font-normal opacity-90">{profile.age}</span>
        </h2>
        
        {#if profile.fakultas || profile.prodi}
          <p class="text-sm text-gray-300 font-medium mt-1">
             {profile.prodi || profile.fakultas}
          </p>
        {/if}

        {#if profile.matchScore}
          <div class="flex items-center text-xs font-medium text-pink-300 mt-1">
            <span class="mr-1">💕</span>
            {profile.matchScore}% Match
          </div>
        {/if}
      </div>

      <button class="bg-white/10 backdrop-blur-md p-2 rounded-full hover:bg-white/20 transition active:scale-95">
        <InfoIcon class="w-6 h-6 text-white" />
      </button>
    </div>

    <div class="h-px w-full bg-white/20 my-3"></div>

    {#if profile.bio}
      <p class="text-sm text-gray-200 leading-relaxed line-clamp-2 opacity-90">
        {profile.bio}
      </p>
    {/if}

    {#if profile.interests && profile.interests.length > 0}
      <div class="flex flex-wrap gap-2 mt-4">
        {#each profile.interests.slice(0, 3) as interest}
          <span class="px-3 py-1 bg-white/10 backdrop-blur-sm border border-white/10 rounded-full text-xs font-semibold text-white/90">
            {interest.icon ?? ''} {interest.name}
          </span>
        {/each}
        {#if profile.interests.length > 3}
          <span class="px-2 py-1 bg-white/10 rounded-full text-xs font-semibold text-white/80">
            +{profile.interests.length - 3}
          </span>
        {/if}
      </div>
    {/if}
  </div>
</div>

<style>
  .text-shadow {
    text-shadow: 0 2px 4px rgba(0,0,0,0.5);
  }
</style>

// src/components/NewCard.tsx
"use client";

import { useState } from "react";
import Image from "next/image";
import { Heart, GraduationCap, Bookmark } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import type { Profile } from "@/app/types/swipe";
import { cn } from "@/lib/utils";

interface SwipeCardProps {
  profile: Profile;
}

export default function NewCard({ profile }: SwipeCardProps) {
  const [currentImageIndex, setCurrentImageIndex] = useState<number>(0);
  const [showDetails, setShowDetails] = useState<boolean>(false);

  const nextImage = () => {
    setCurrentImageIndex((prevIndex) =>
      prevIndex === profile.Photos.length - 1 ? 0 : prevIndex + 1
    );
  };

  const prevImage = () => {
    setCurrentImageIndex((prevIndex) =>
      prevIndex === 0 ? profile.Photos.length - 1 : prevIndex - 1
    );
  };

  const displayName = profile.fullname || profile.name;

  const allImages =
    profile.Photos && profile.Photos.length > 0
      ? profile.Photos
      : ["/placeholder.svg?height=600&width=400"];

  return (
    <div className="relative w-full max-w-md mx-auto h-[70vh]  rounded-3xl shadow-lg box ">
      <div className="relative h-full rounded-3xl ">
        {/* Main Image */}
        <div className="absolute inset-0 rounded-3xl  ">
          <Image
            src={allImages[currentImageIndex] || "/placeholder.svg"}
            alt={`Foto ${displayName}`}
            fill
            className="object-cover transition-opacity rounded-3xl duration-300 "
            priority
            onError={(e) => {
              // Fallback to placeholder if image fails to load
              e.currentTarget.src = "/placeholder.svg?height=600&width=400";
            }}
          />
        </div>

        {/* Image navigation areas */}
        {allImages.length > 1 && (
          <div className="absolute inset-x-0 top-0 h-full flex">
            <div
              className="w-1/2 h-full cursor-pointer"
              onClick={prevImage}
            ></div>
            <div
              className="w-1/2 h-full cursor-pointer"
              onClick={nextImage}
            ></div>
          </div>
        )}

        {/* Image indicators */}
        {allImages.length > 1 && (
          <div className="absolute top-4 inset-x-0 px-4">
            <div className="flex space-x-1">
              {allImages.map((_, index) => (
                <div
                  key={index}
                  className={cn(
                    "h-1 flex-1 rounded-full transition-all duration-300",
                    index === currentImageIndex ? "bg-white" : "bg-white/40"
                  )}
                ></div>
              ))}
            </div>
          </div>
        )}

        {/* Match Score Badge */}
        {profile.matchScore && (
          <div className="absolute top-4 right-4 bg-pink-500 text-white px-3 py-1 rounded-full text-sm font-bold">
            <Heart className="inline mr-1" size={14} fill="white" />
            {profile.matchScore}% Match
          </div>
        )}

        {/* Profile info overlay */}
        <div
          className={cn(
            "absolute bottom-0 inset-x-0 bg-gradient-to-t from-black/80 via-black/50 to-transparent p-6 text-white transition-all duration-300 cursor-pointer rounded-3xl",
            showDetails ? "h-2/3" : "h-auto"
          )}
          onClick={() => setShowDetails(!showDetails)}
        >
          <div className="flex items-end justify-between">
            <h3 className="text-3xl font-bold">
              {displayName}, {profile.age}
            </h3>
            <button className="rounded-full bg-white/20 p-2 backdrop-blur-sm">
              <Bookmark className="h-5 w-5 text-white" />
            </button>
          </div>

          {/* Academic info */}
          {(profile.fakultas || profile.prodi) && (
            <div className="flex items-center gap-1 mt-2 text-white/80">
              <GraduationCap className="h-4 w-4" />
              <span className="text-sm">
                {profile.prodi && profile.fakultas
                  ? `${profile.prodi}, ${profile.fakultas}`
                  : profile.fakultas || profile.prodi}
              </span>
            </div>
          )}

          {/* Expandable details */}
          <div
            className={cn(
              "transition-all duration-300 overflow-hidden",
              showDetails
                ? "max-h-[500px] opacity-100 mt-4"
                : "max-h-0 opacity-0"
            )}
          >
            <div className="space-y-4">
              {profile.bio && (
                <div>
                  <h4 className="text-sm font-medium text-white/80 mb-1">
                    About
                  </h4>
                  <p className="text-sm">{profile.bio}</p>
                </div>
              )}

              {profile.interests && profile.interests.length > 0 && (
                <div>
                  <h4 className="text-sm font-medium text-white/80 mb-2">
                    Interests
                  </h4>
                  <div className="flex flex-wrap gap-2">
                    {profile.interests.map((interest, index) => (
                      <Badge
                        key={index}
                        className="bg-white/20 text-white hover:bg-white/30"
                      >
                        {interest.name}
                      </Badge>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Tap to expand hint */}
          {!showDetails && (
            <div className="mt-2 text-white/60 text-xs">
              Tap to see more details
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
