// src/app/swipe/components/SkeletonCard.tsx
import React from 'react';

const SkeletonCard = () => {
  return (
    <div className="space-y-6">
      {/* Card Skeleton */}
      <div className="bg-white rounded-3xl shadow-lg overflow-hidden">
        {/* Image Placeholder */}
        <div className="bg-gray-200 border-2 border-dashed rounded-xl w-full h-96 animate-pulse" />
        
        {/* Profile Info Placeholder */}
        <div className="p-6">
          <div className="flex justify-between items-start">
            <div>
              <div className="h-7 bg-gray-200 rounded w-40 mb-2 animate-pulse"></div>
              <div className="h-5 bg-gray-200 rounded w-60 animate-pulse"></div>
            </div>
          </div>
        </div>
      </div>
      
      {/* Action Buttons Placeholder */}
      <div className="flex justify-center space-x-8">
        <div className="h-16 w-16 rounded-full bg-gray-200 animate-pulse"></div>
        <div className="h-16 w-16 rounded-full bg-gray-200 animate-pulse"></div>
      </div>
    </div>
  );
};

export default SkeletonCard;

// src/lib/components/SkeletonCard.svelte
<div class="w-full aspect-3/4 bg-gray-200 rounded-3xl animate-pulse relative overflow-hidden shadow-lg border border-gray-100">
  <div class="absolute bottom-0 left-0 w-full h-1/2 bg-linear-to-t from-gray-300 to-transparent"></div>
  
  <div class="absolute bottom-6 left-6 right-6 space-y-3">
    <div class="h-8 bg-gray-400/50 rounded-lg w-2/3"></div>
    <div class="h-4 bg-gray-400/30 rounded w-full"></div>
    <div class="h-4 bg-gray-400/30 rounded w-4/5"></div>
    <div class="flex gap-2 mt-2">
      <div class="h-6 w-16 bg-gray-400/30 rounded-full"></div>
      <div class="h-6 w-20 bg-gray-400/30 rounded-full"></div>
    </div>
  </div>
</div>
